
server:
  port: 8080
shiro:
  loginUrl: /user/login         # Todo
  successUrl: /                 # Todo
  unauthorizedUrl: /user/login  # Todo
mybatis:
  mapper-locations: classpath*:/mapper/* # Locations of Mapper xml config file.
  type-handlers-package: com.online.office.mybatisHandler
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/office?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
